services:
  app:
    image: docker.tolq3.ru/contractor:build-${BUILD_NUMBER_ACCOUNTOWNER}
    build:
      context: .
    command: >
      sh -c "python manage.py collectstatic --noinput && 
      python manage.py migrate && gunicorn contractor.wsgi:application --bind 0.0.0.0:8000"
    ports:
        - 8000:8000
    volumes:
      - ${PWD}/statica:/app/statica
      - ${PWD}/.env:/app/.env:ro
      - ${PWD}/apps:/app/apps

volumes:
  app-volume: