# Generated by Django 5.1.6 on 2025-03-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_historicalmembers_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалена'),
        ),
    ]
