# Generated by Django 5.1.4 on 2025-01-05 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': 'Участник Проекта', 'verbose_name_plural': 'Участники проекта'},
        ),
    ]
