# Generated by Django 5.1.4 on 2025-01-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_members_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='arhived',
        ),
        migrations.AddField(
            model_name='project',
            name='base_url',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Базовый URL проекта'),
        ),
    ]
