# Generated by Django 5.1.2 on 2024-11-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Описание')),
                ('arhived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ДТО',
                'verbose_name_plural': 'ДТО',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(blank=True, choices=[(1, 'Integer'), (2, 'String'), (3, 'List'), (4, 'Dictionary'), (5, 'ForeignKey')], default=None, null=True)),
                ('value', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Поле ДТО',
                'verbose_name_plural': 'Поял ДТО',
            },
        ),
    ]
