# Generated by Django 5.1.6 on 2025-03-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0003_remove_historicalmembers_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='dto',
        ),
        migrations.RemoveField(
            model_name='members',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalMembers',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
