# Generated by Django 5.1.4 on 2025-01-05 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'Поле ДТО', 'verbose_name_plural': 'Поля ДТО'},
        ),
        migrations.AlterModelOptions(
            name='historicalfield',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Поле ДТО', 'verbose_name_plural': 'historical Поля ДТО'},
        ),
    ]
