# Generated by Django 5.1.7 on 2025-03-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0004_remove_members_dto_remove_members_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='historicalfield',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Описание'),
        ),
    ]
