# Generated by Django 5.1.4 on 2025-01-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0004_alter_field_options_alter_historicalfield_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dto',
            name='arhived',
        ),
        migrations.RemoveField(
            model_name='historicaldto',
            name='arhived',
        ),
        migrations.AddField(
            model_name='dto',
            name='base_url',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Базовый URL DTO'),
        ),
        migrations.AddField(
            model_name='historicaldto',
            name='base_url',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Базовый URL DTO'),
        ),
    ]
