# Generated by Django 5.1.4 on 2025-01-24 17:28

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dto', '0005_remove_dto_arhived_remove_historicaldto_arhived_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPact',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Идентификатор')),
                ('method', models.PositiveIntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'PUT'), (4, 'PATCH'), (5, 'DELETE'), (6, 'OPTIONS'), (7, 'HEAD')], default=1, verbose_name='Метод запроса')),
                ('base_url', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Базовый URL запроса')),
                ('body', models.TextField(blank=True, default=None, null=True, verbose_name='Тело запроса')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dto', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dto.dto', verbose_name='DTO')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Контракт',
                'verbose_name_plural': 'historical Контракты',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Pact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('method', models.PositiveIntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'PUT'), (4, 'PATCH'), (5, 'DELETE'), (6, 'OPTIONS'), (7, 'HEAD')], default=1, verbose_name='Метод запроса')),
                ('base_url', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Базовый URL запроса')),
                ('body', models.TextField(blank=True, default=None, null=True, verbose_name='Тело запроса')),
                ('dto', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pact', to='dto.dto', verbose_name='DTO')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=1024)),
                ('pact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='pact.pact')),
            ],
            options={
                'verbose_name': 'Заголовок',
                'verbose_name_plural': 'Заголовки',
            },
        ),
        migrations.CreateModel(
            name='QueryParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('value', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('pact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_params', to='pact.pact')),
            ],
            options={
                'verbose_name': 'Параметр запроса',
                'verbose_name_plural': 'Параметры запроса',
            },
        ),
    ]
